#+STARTUP: overview
#+TITLE: Keluar dari Familie Wohnung di Aachen Jerman

Jakarta, 29 Juni 2021 - Yohan Fajar Sidik

Rumah sewa kami di Jerman adalah Familie Wohnung yang berukuran 46
meter persegi.  Untuk menyewa rumah ini, biasanya penyewa harus
memberikan uang deposit sebesar 2 atau 3 kali dari harga sewa. Uang
deposit ini disebut Kaution dalam bahasa Jerman. Uang Kaution ini bisa
dipotong apabila ada kerusakan saat akan keluar dari rumah sewa
tersebut.

Dalam kontrak rumah, biasanya ada hal-hal yang harus dilakukan apabila
akan keluar dari rumah sewa.  Misalnya, tembok rumah harus dicat
kembali dan harus mengeluarkan semua barang-barang (furnitur) apabila
si pemilik rumah tidak menghendaki ada penyewa berikutnya
(Nachmieter). Alasannya bisa dikarenakan rumah tersebut mau dijual
atau mau direnovasi. Berikut ini saya mau berbagi perihal pengalaman
kami dalam mengecat rumah dan mengeluarkan barang-barang furnitur.

* Mengecat

Peralatan cat yang murah bisa diperoleh di Action (Vaals). Untuk
mengecat tembok, belilah alat cat rol baik yang ukuran besar atau
kecil. Untuk mengecat pintu juga diperlukan alat cat rol. Tetapi,
rol-nya khusus untuk kayu. Rol tersebut dari busa.
  
* Mengeluarkan barang-barang  

Barang-barang bisa dikeluarkan dengan cara diberikan/dijual ke teman
atau melalui ebay kleinanzeigen.

Barang-barang sisa lainnya bisa diambil oleh petugas Stadt. Tetapi, kita harus
mendaftar dan membayar untuk itu. Berikut ini adalah tautan untuk mendaftar
[[https://serviceportal.aachen.de/suche/-/vr-bis-detail/dienstleistung/5811/show][sperrmüll]].

Sebaiknya barang-barang yang akan diambil oleh Stadt diturunkan pada
hari yang sama dengan pengambilan oleh Stadt. Stadt akan mengambil
barang-barang pada jam 09:00. Jadi barang-barang bisa diturunkan pada
jam 06:00-08:00. Hal ini untuk menghindari barang-barang ilegal yang
disimpan oleh orang-orang yang tidak bertanggung jawab. Apabila tidak
memungkinkan mengeluarkan barang pada hari yang sama dengan
pengambilan, maka lakukankan H-1.
