#+STARTUP: overview
#+TITLE: Perjalanan Pulang Jerman-Indo Tanggal 26 Juni 2021

Jakarta, 29 Juni 2021 - Yohan Fajar Sidik

* Bagian 1 - Dokumen yang dibutuhkan
  
Dalam situasi pandemi corona seperti sekarang ini, berikut ini adalah dokumen
yang dibutuhkan untuk melakukan perjalanan dari Jerman ke Indonesia.

- Tiket pesawat
- Paspor
- Hasil negatif tes PCR
- eHAC
- Bukti booking hotel (jika karantina di hotel)
  
** Tes Corona

Saat ini tempat tes PCR dapat dengan mudah ditemukan di banyak tempat
di Jerman.  Di tempat saya tinggal di Aachen, tempat tes PCR misalnya
bisa dilakukan di [[https://aachentest.de][Medicare]]. Total biaya adalah 90 Euro. Berdasarkan
info dari website-nya, biaya tersebut terdiri dari biaya booking
sebesar 31.62 Euro yang dibayar di tempat tes. Sedangkan biaya sisanya
adalah biaya lab yang akan ditagih dalam bentuk invoice dan akan
dikirim ke rumah masing-masing pengambil tes.

Tes PCR yang lebih murah dapat dilakukan di [[https://flughafen-duesseldorf.ecocare.center/en/][EcoCare]] di bandara
Düsseldorf.  Biaya paling murah adalah 59 Euro untuk hasil dalam waktu
24 jam. Sedangkan biaya paling mahal adalah 149 Euro untuk hasil dalam
waktu 1 jam.  Biaya tes pun dapat dibayar di tempat. Ini memudahkan
bagi orang-orang yang akan pulang habis ke Indonesia. Dikarenakan
biaya tes dapat dilunasi pada saat itu juga.

** eHAC

eHAC adalah Indonesia Health Alert Card. eHAC dapat diisi melalui
aplikasi android atau iOS. Yang dibutuhkan oleh petugas di bandara CGK
adalah barcode dari aplikasi eHAC. Barcode tersebut dapat ditunjukkan
langsung dari HP. Sebagai tips, eHAC dapat juga diprint. Caranya
adalah login eHAC melalui komputer dan bukalah [[https://inahac.kemkes.go.id][website eHAC]]. Kemudian
download pdf hasil isian eHAC di website tersebut.

** Tempat Karantina

Ada 2 pilihan tempat karantina, yaitu wisma atlet dan hotel. Biaya karantina
di wisma atlet ditanggung pemerintah. Sementara biaya hotel ditanggung sendiri.

Hotel karantina dapat dipesan melalui 2 cara, yaitu melalui travel agent atau
menghubungi hotel secara langsung. Travel agent biasanya menawarkan biaya
hotel yang lebih murah dibandingkan dengan menghubungi secara langsung.
Kami memilih menghubungi hotel secara langsung walaupun biayanya lebih mahal.
Ini karena kami tidak mau kena penipuan. 

* Bagian 2 - Pengalaman pulang Jerman-Indo saat pandemi
  
Pada awalnya kami tidak ada bayangan sama sekali bagaimana situasi perjalanan
menggunakan pesawat di saat pandemi seperti sekarang ini. Setelah melakukan
perjalanan dari Jerman ke Indonesia, barulah kami merasakan situasinya.

Sebelum keberangkatan ke Indonesia. Siapkanlah dokumen yang
dibutuhkan. Dokumen yang dibutuhkan dapat dibaca pada bagian 1.
Simpanlah tiket pesawat, paspor, dan hasil negatif tes PCR dalam wadah
yang sama.  Dokumen tersebut sering diminta oleh petugas. Misalnya
saat check in dan saat transit. Adapun eHAC dan bukti booking hotel
digunakan nanti setelah sampai di Indonesia.

Kami berangkat dari bandara Franfurt pada pukul 22:20 CEST dan sampai
di bandara Dubai pada pukul 06:00 waktu Dubai. Perjalanan selanjutnya
adalah pukul 10:45 dan sampai di bandara CGK di Jakarta pada pukul
22:00.

Perihal jumlah penumpang. Penumpang pesawat dari Franfurt ke Dubai
tidaklah banyak sehingga banyak kursi kosong.  Kami jadi merasa tenang
melakukan perjalanan dari Frankfurt ke Dubai.  Sedangkan penumpang
pesawat dari Dubai ke Jakarta sangatlah ramai. Kursi depan, belakang,
dan samping terisi oleh penumpang. Kami merasa kurang nyaman
dengan kondisi penuh penumpang ini. Apalagi saat waktunya makan yang
mengharuskan untuk membuka masker. Walaupun sebenarnya, semua
penumpang telah melakukan tes PCR.  Jadi secara teoritis seharusnya
aman.

Saat transit di Dubai, tidak ada protokol khusus. Hanya perlu
menunjukkan kembali paspor dan hasil tes PCR. Di Dubai sangatlah
ramai. Bahkan cukup sulit untuk mencari tempat duduk.

Setelah pesawat mendarat di bandara CGK. Kami pun keluar dari pesawat
dan menuju ke tempat pengisian lembar pemeriksaan kesehatan. Setelah
lembar pemeriksaan kesehatan diisi, kemudian antri untuk pengecekan
barcode eHAC.  Setelah itu, antri kembali untuk pengecekan validitas
dari hasil tes corona. Petugas kemudian akan mengisi hasil pengecekan
validitas hasil tes corona di lembar pemeriksaan kesehatan yang tadi
diisi.  Petugas juga akan bertanya mengenai tempat karantina, apakah
di hotel atau di wisma atlet.  Kemudian petugas akan memberi stempel
hotel atau wisma atlet di lembar pemeriksaan kesehatan. Setelah proses
ini, kemudian menuju ke pos imigrasi. Setelah dari pos imigrasi
kemudian menuju ke tempat pengambilan bagasi. Selanjutnya, menuju ke
pemeriksaan bea dan cukai. Proses ini kami lalui sekitar 45 menit. 

Setelah proses di atas, selanjutnya adalah menuju ke tempat karantina.
Petugas di sana akan mengarahkan sesuai dengan pilihan apakah di hotel
atau wisma atlet.  Kami memilih hotel untuk tempat karantina. Di pintu
keluar gate 1, di sana telah ada seseorang dari hotel yang menunggu
kami. Orang tersebut meminta bukti booking hotel dan paspor. Paspor
kami diambil oleh orang tersebut untuk diberikan ke supir yang
mengantar ke hotel. Setelah tiba di hotel, supir membantu membawa
barang bawaan kami dan juga mengantarkan kami ke resepsionis
hotel. Supir tersebut kemudian memberikan paspor kami ke resepsionis.
Setelah urusan bayar hotel selesai, selanjutnya paspor kami
dikembalikan dan kami kemudian diminta untuk menuju ke ruangan tes
PCR. Setelah tes PCR, selanjutnya kembali ke resepsionis dan
resepsionis akan memberikan kunci kamar hotel.

Itulah pengalaman kami melakukan perjalanan dari Jerman ke
Indonesia. Mulai dari persiapan keberangkatan dan sampai dengan tempat
karantina di hotel.

* Bagian 3 - Daftar IMEI HP

Apabila HP dibeli di luar negeri, maka IMEI HP perlu didaftarkan ke
bea cukai di bandara CGK di terminal 3.

Dokumen yang perlu dipersiapkan adalah:

- surat keterangan selesai karantina
- paspor
- boarding pass
- barcode

Barcode diperoleh setelah mengisi formulir pendaftaran IMEI melalui:

- [[https://www.beacukai.go.id/register-imei.html][Website bea cukai]]
- Aplikasi bea cukai

Pembebasan pajak bisa diperoleh apabila jumlah barang setiap penumpang
tidak lebih dari 500 USD. Jadi, apabila anda merupakan penumpang
keluarga (minimal suami dan istri), maka daftarkanlah IMEI HP tersebut
masing-masing agar harga barang tersebut tidak melebihi 500 USD.
